[versions]
minecraft = "26.1"
compatibility = "26.1.x"
fabric-api = "0.155.2+26.1.2"

odin = "7FcnBdo7"
odin-compat = "*"
snowbird = "2026.09.4+26.1"
cascade = "2026.10.1+26.1"
updater = "2026.09.2+26.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

odin = { module = "maven.modrinth:odin", version.ref = "odin" }
snowbird = { module = "foo.starred:snowbird", version.ref = "snowbird" }
cascade = { module = "foo.starred:cascade", version.ref = "cascade" }
updater = { module = "foo.starred:updater", version.ref = "updater" }
