[versions]
minecraft = "26.2"
compatibility = "26.2.x"
fabric-api = "0.158.0+26.2"

odin = "9bsBi70Z"
odin-compat = ">=0.3.6"
snowbird = "2026.09.4+26.2"
cascade = "2026.10.1+26.2"
updater = "2026.09.2+26.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

odin = { module = "maven.modrinth:odin", version.ref = "odin" }
snowbird = { module = "foo.starred:snowbird", version.ref = "snowbird" }
cascade = { module = "foo.starred:cascade", version.ref = "cascade" }
updater = { module = "foo.starred:updater", version.ref = "updater" }
